# Generated by Django 4.1.7 on 2023-03-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='img.jpeg', upload_to='image/%Y', verbose_name='Изобранжение'),
            preserve_default=False,
        ),
    ]
